services:
  # api:
  #   image: journal-api:latest
  #   environment:
  #     DB_URL: db
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: journal
  broker:
    image: rabbitmq:4.3.2-management
    ports:
      - "5672:5674"
      - "15672:15672" # for browser management interface
